//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANALYS_SYSTEM_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Struct
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Attributes_List { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<int> Type_ID { get; set; }
    
        public virtual Document_Type Document_Type { get; set; }
    }
}
