//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANALYS_SYSTEM_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_Request
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Lastname { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<int> Request_Status_ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
    
        public virtual Request_Status Request_Status { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
